name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set App Version
        run: echo "APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker build -t ghcr.io/${{ github.actor }}/${{ github.repository }}/myapp:latest .
          docker push ghcr.io/${{ github.actor }}/${{ github.repository }}/myapp:latest

  deploy-vps:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Docker Compose and Nginx Config to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          source: docker-compose.yml, nginx/nginx.conf
          target: ~/app

      - name: Pull and Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd ~/app
            echo "${{ secrets.GITHUB_TOKEN }}" 
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose pull && docker compose up -d
